---
- name: Write Nginx env file
  hosts: localhost
  connection: local
  become: true

  # vars:
  #   domain: test.devopswiki.info

  tasks:
    - name: Fetch backend private IP from SSM
      ansible.builtin.command:
        cmd: >
          aws ssm get-parameter
          --name devopswiki-infra-{{ env }}-be_private_ip
          --query Parameter.Value
          --output text
          --region {{ region }}
      register: be_ip
      changed_when: false

    - name: Create /opt/app directory
      ansible.builtin.file:
        path: /opt/app
        state: directory
        owner: yaw
        group: yaw
        mode: "0755"

    - name: Write .env file
      ansible.builtin.copy:
        dest: /opt/app/.env
        owner: yaw
        group: yaw
        mode: "0644"
        content: |
          BE_PRIVATE_IP={{ be_ip.stdout }}
          SERVER_NAME={{ domain }}
          CERT_DOMAIN={{ domain }}
