---
- name: Write backend env file
  hosts: localhost
  become: true

  tasks:
    - name: Fetch postgres user from SSM
      ansible.builtin.command:
        cmd: >
          aws ssm get-parameter
          --name devopswiki-infra-{{ env }}-postgres_user
          --with-decryption
          --query Parameter.Value
          --output text
          --region {{ region }}
      register: pg_user
      changed_when: false

    - name: Fetch postgres password from SSM
      ansible.builtin.command:
        cmd: >
          aws ssm get-parameter
          --name devopswiki-infra-{{ env }}-postgres_password
          --with-decryption
          --query Parameter.Value
          --output text
          --region {{ region }}
      register: pg_password
      changed_when: false

    - name: Create /opt/app directory
      ansible.builtin.file:
        path: /opt/app
        state: directory
        owner: yaw
        group: yaw
        mode: "0755"

    - name: Write .env file
      ansible.builtin.copy:
        dest: /opt/app/.env
        owner: yaw
        group: yaw
        mode: "0600"
        content: |
          POSTGRES_USER={{ pg_user.stdout }}
          POSTGRES_PASSWORD={{ pg_password.stdout }}
